apiVersion: apps/v1
kind: Deployment
metadata:
    name: bookstore-deployment
    labels:
        app: bookstore
spec:
    replicas: 2
    selector:
        matchLabels:
            app: bookstore
    template:
        metadata:
            labels:
                app: bookstore
        spec:
            containers:
            - name: bookstore
              image: bookstoreapp.azurecr.io/bookstoreapp-spring:latest
              ports:
              - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
    name: bookstore-service
spec:
    selector:
        app: bookstore
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
    name: bookstore-external-service
spec:
    selector:
        app: bookstore
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8081
          nodePort: 30000
