apiVersion: apps/v1
kind: Deployment
metadata:
    name: bookstore-deployment
    labels:
        app: bookstore
spec:
    replicas: 2
    selector:
        matchLabels:
            app: bookstore
    template:
        metadata:
            labels:
                app: bookstore
        spec:
            containers:
            - name: bookstore
              image: bookstoreapp.azurecr.io/bookstoreapp-spring:latest
              ports:
              - containerPort: 8081